### ISSUE TITLE
git tag is not handled properly

### ISSUE THREAD

**Issue by kikonen** [kikonen/bower_vendor#8]
For example, following resolves incorrectly.

``` yaml
lodash:
  version: 4.0.0
  git: git@github.com:lodash/lodash.git
  tag: 4.0.0-npm-packages
  assets:
  - dist/lodash.js
```

=> 

``` json
{
  "name": "autogenerated",
  "dependencies": {
    "lodash": "git@github.com:lodash/lodash.git#4.0.0-npm-packages",
  },
  "resolutions": {
    "lodash": "git@github.com:lodash/lodash.git#4.0.0-npm-packages",
  }
}
```

=> it resolves into "branch" https://github.com/lodash/lodash/tree/npm-packages which causes incorrect result, since contents of branch is not suitable format to be consumed.

References:
- https://github.com/bower/spec/blob/master/json.md
